version: '2'
services:
  mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
  backend:
    build: backend/app
    ports:
      - "3000:8080"
    volumes:
      - ./backend/app/src:/backend/src
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  frontend:
      build: public
      ports:
        - "4200:4200"
      volumes:
        - ./public/src:/frontend/src
