version: '2'
services:
  mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
  node-app:
    build: app
    ports:
      - "4000:8080"
    volumes:
      - ./app/src:/myapp/src
    depends_on:
      - mongo
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DATABASE=app
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
