version: '2'
services:
  mongo:
      image: mongo:latest
      ports:
        - "27017:27017"
  node-app:
    build: app
    ports:
      - "3000:8080"
    volumes:
      - ./app/src:/myapp/src
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
